name: build
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the source from GitHub
              uses: actions/checkout@v2
            
            # Compile SCSS to CSS (Node.js)
            - name: Setup Node.js environment
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: 10.x
            - name: Intall dependencies and run sass-compile
              run: |
                  npm install
                  npm run sass-compile
          
            # Run MkDocs (Python)
            - name: Setup Python environment
            - uses: actions/setup-python@v2
              with:
                python-version: 3.x
            - name: Install dependencies and run mkdocs
              run: |
                pip install wheel mkdocs
                mkdocs gh-deploy --force
